title: INF-6010 Praktisk Entreprenørskap

description: > # this means to ignore newlines until "contact:"
  INF-6010 Praktisk Entreprenørskap i Kirkenes

contact:
  email: lars.ailo.bongo@uit.no
  name: Lars Ailo Bongo

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
